fun main() {
    val usuario = Modelos.Usuario()
    println(usuario)
    println(usuario.id)
    println(usuario.nombres)
    println(usuario.apellidos)
    println(usuario.correo)
    println(usuario.contraseña)
    println(usuario.telefono)
    println(usuario.direccion)
    println()

    val categoria = Modelos.Categoria()
    println(categoria)
    println(categoria.id)
    println(categoria.nombre)
    println(categoria.descripcion)
    println()

    val productos = Modelos.Productos()
    println(productos)
    println(productos.id)
    println(productos.nombre)
    println(productos.fecha_entrada)
    println(productos.fecha_vence)
    println(productos.estado)
    println(productos.cantidad)
    println(productos.precio_entrada)
    println(productos.precio_salida)
    println()

    val factura = Modelos.Factura()
    println(factura)
    println(factura.id)
    println(factura.fecha)
    println(factura.monto_total)
    println(factura.cantidad)
    println(factura.precio_unitario)
    println()

    val movimientos = Modelos.Movimientos()
    println(movimientos)
    println(movimientos.id)
    println(movimientos.fecha)
    println(movimientos.tipo)
    println()

    val alerta = Modelos.Alerta()
    println(alerta)
    println(alerta.id)
    println(alerta.nombre)
    println(alerta.stock_minimo)
    println(alerta.stock)
    println()

    val venta = Modelos.Venta()
    println(venta)
    println(venta.id)
    println(venta.cantidad_a_vender)
}